image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'Install pre-requisites' # runs during prebuild
    command: jupyter-lab --ServerApp.token="" --ServerApp.ip="0.0.0.0" --ServerApp.allow_origin="*"
  - command: ./printJupyterURL.sh
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-browser
  - port: 8050
    onOpen: open-preview
